version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  gotodo:
    image: "cloud.canister.io:5000/mathieux51/gotodo:latest"
    ports:
      - "3000:3000"
    links:
      - redis
    environment:
      - REDIS_HOST=redis
