apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjbG91ZC5jYW5pc3Rlci5pbzo1MDAwIjp7InVzZXJuYW1lIjoibWF0aGlldXg1MSIsInBhc3N3b3JkIjoiRDRadXZ3WUFhQ2JOOWtQIiwiZW1haWwiOiJtYXRoaWV1eDUxQGdtYWlsLmNvbSIsImF1dGgiOiJiV0YwYUdsbGRYZzFNVHBFTkZwMWRuZFpRV0ZEWWs0NWExQT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
