jobs:
  test:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/redis:alpine
    steps:
      - checkout
      - run: make get
      - run:
          name: waiting for Redis to be ready
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run: make test
  build_and_push_docker_image:
    machine: true
    steps:
      - checkout
      - run: make docker-build
      - run: make docker-login
      - run: make docker-push
  deploy:
    machine: true
    steps:
      - checkout

workflows:
  version: 2
  build:
    jobs:
      - test
      - build_and_push_docker_image:
          requires:
            - test
      - kubernetes/install
      - gcp-cli/install_and_initialize_cli
      - deploy: 
          requires: 
            - build_and_push_docker_image
