jobs:
  test:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/redis:alpine
    steps:
      - checkout
      - run:
          name: printenv 
          command: printenv 
      - run: make get
      - run:
          name: waiting for Redis to be ready
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run: 
          make test

# build_and_push_docker_image:
#   machine: true
#   steps:
#     - checkout
#     - run: make docker-build
#     - run: make docker-login
#     - run: make docker-push
# deploy:
#   machine: true
#   steps:
#     - checkout
#     - kubernetes/install
#     - helm/install-helm-client
#     - run: make   
#     - run: make helm-install

version: 2.1
orbs:
  helm: circleci/helm@0.1.3
  gcp-cli: circleci/gcp-cli@1.8.2
  kubernetes: circleci/kubernetes@0.3.0
workflows:
  version: 2
  build:
    jobs:
      - test
