version: 2.1
# orbs:
#   helm: circleci/helm@0.1.2
#   gcp-gke: circleci/gcp-gke@0.2.0
commands:
  # k8s-install:
  #   description: "Install `kubectl` if not already installed."
  #   steps:
  #     - k8s/install
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.7
      - image: circleci/redis:alpine
    steps:
      - checkout
      - run: make get
      - run: make test
  build:
    docker:
      - image: circleci/golang:1.12.7
    steps:
      - checkout
      - run: make build
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
        requires:
          - test
      # - k8s-install
      # - gcp-gke/install
      # - gcp-gke/init
      # - helm/init ⚠️
      # - run:
      #     name: "check kubetcl and helm versions"
      #     command: |
      #       kubectl cluster-info
      #       helm version
      # - run:
      #     name: "helm install"
      #     command: |
      #       make install
      # - run:
      #     name: "go test"
      #     command: |
      #       make test
