version: 2.1
orbs:
  helm: circleci/helm@0.1.2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.7
      - image: circleci/redis:alpine
    steps:
      - checkout
      - run: make get
      - run:
          name: waiting for Redis to be ready
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run: make test
  build_and_deploy:
    docker:
      - image: circleci/golang:1.12.7
    steps:
      - checkout
      - run: make get
      - run: make build

# connect to cluster
# create configmap with binary
# helm install

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
