version: 2.1
# orbs:
#   helm: circleci/helm@0.1.2
#   gcp-gke: circleci/gcp-gke@0.2.0
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.7
    steps:
      - checkout
      - run: make build
  test:
    docker:
      - image: circleci/golang:1.12.7
      - image: circleci/redis:alpine
    steps:
      - checkout
      - run: make get
      - run: make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
