version: 2.1
orbs:
  helm: circleci/helm@0.1.3
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/redis:alpine
    steps:
      - checkout
      - run: make get
      - run:
          name: waiting for Redis to be ready
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run: make test
  build_and_deploy:
    docker:
      - image: circleci/helm:2.14.0
    steps:
      - checkout
      - run: make docker-build
      - run: make docker-login
      - run: make docker-push
      - run: make del 
      - run: make helm-install

# connect to cluster
# create configmap with binary
# helm install

workflows:
  version: 2
  build:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test
