version: 2.1
orbs:
  helm: circleci/helm@0.1.2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/redis:alpine
    steps:
      - checkout
      - run: make get
      - run:
          name: waiting for Redis to be ready
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run: make test
  build_and_push_docker_image:
    machine: true
    steps:
      - checkout
      - run: make docker-build
      - run: make docker-login
      - run: make docker-push
  gcloud:
    docker:
      - image: google/cloud-sdk
      - image: alpine/helm
    steps:
      - checkout
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run: helm install 
# connect to cluster
# create configmap with binary
# helm install

workflows:
  version: 2
  build:
    jobs:
      - test
      - build_and_push_docker_image:
          requires:
            - test
      - gcloud: 
          requires: 
            - build_and_push_docker_image
