# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Install kubelet, kubeadm and kubectl"
          command: |
            sudo apt-get update && sudo apt-get install -y apt-transport-https curl
            curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
            cat \<\<EOF >/etc/apt/sources.list.d/kubernetes.list
            deb https://apt.kubernetes.io/ kubernetes-xenial main
            EOF
            sudo apt-get update
            sudo apt-get install -y kubelet kubeadm kubectl
            apt-mark hold kubelet kubeadm kubectll
      - run:
          name: "install helm"
          command: |
            curl -LO https://git.io/get_helm.sh
            chmod 700 get_helm.sh
            ./get_helm.sh
      - run:
          name: "init cluster"
          command: |
            kubeadm init
  # build:
  #   docker:
  #     # specify the version
  #     - image: circleci/golang:1.9
  #     # Specify service dependencies here if necessary
  #     # CircleCI maintains a library of pre-built images
  #     # documented at https://circleci.com/docs/2.0/circleci-images/
  #     # - image: circleci/postgres:9.4
  #   #### TEMPLATE_NOTE: go expects specific checkout path representing url
  #   #### expecting it in the form of
  #   ####   /go/src/github.com/circleci/go-tool
  #   ####   /go/src/bitbucket.org/circleci/go-tool
  #   working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
  #   steps:
  #     # specify any bash command here prefixed with `run: `
  #     - run: go get -v -t -d ./...
  #     - run: go test -v ./...
