version: 2.1
orbs:
  helm: circleci/helm@0.1.2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/redis:alpine
    steps:
      - checkout
      - run: make get
      - run:
          name: waiting for Redis to be ready
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run: make test
  build_and_deploy:
    machine: true
    steps:
      - checkout
      - run: curl -LO https://git.io/get_helm.sh
      - run: chmod 700 get_helm.sh
      - run: ./get_helm.sh
      - run: make docker-build
      - run: make docker-login
      - run: make docker-push
      - run: make del 
      - run: make helm-install


# connect to cluster
# create configmap with binary
# helm install

workflows:
  version: 2
  build:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test
