apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: APP_NAME
  name: {{ .Values.APP_NAME }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: {{ .Values.APP_NAME }}
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis
          image: {{ .Values.IMAGE_NAME }}
          name: {{ .Values.APP_NAME }}
          command: ["/bin/sh"]
          tty: true
          stdin: true
          # command: ["./{{ .Values.BINARY_NAME }}"]
          ports:
            - containerPort: {{ .Values.IMAGE_PORT }}
      restartPolicy: Always
