apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gotodo
  name: gotodo
spec:
  type: NodePort
  ports:
    - nodePort: 30010
      port: 3001
      targetPort: 30001
  selector:
    io.kompose.service: gotodo
