apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.APP_NAME }}
  labels:
    service: {{ .Values.APP_NAME }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.IMAGE_PORT }}
      targetPort: {{ .Values.IMAGE_PORT }}
  selector:
    service: {{ .Values.APP_NAME }}
