apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gotodo
  name: gotodo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: gotodo
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis
          image: {{ .Values.imageName }}
          name: gotodo
          ports:
            - containerPort: 3001
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
