apiVersion: v1
kind: Service
metadata:
  name: gotodo
  labels:
    io.kompose.service: gotodo
spec:
  type: NodePort
  ports:
    - nodePort: 30010
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: gotodo
