apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: APP_NAME
  name: {{ .Values.APP_NAME }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: {{ .Values.APP_NAME }}
    spec:
      containers:
        - name: {{ .Values.APP_NAME }}
          image: {{ .Values.IMAGE_NAME }}:{{ .Values.VERSION }}
          env:
            - name: REDIS_HOST
              value: redis
          # tty: true
          # stdin: true
          command: ["/go/gotodo/{{ .Values.BINARY_NAME }}"]
          ports:
            - containerPort: {{ .Values.IMAGE_PORT }}
      imagePullSecrets:
        - name: registrycredentials 
      restartPolicy: Always
