apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - image: {{ .Values.redisImage }}
          name: redis
          ports:
            - containerPort: {{ .Values.redisPort }}
      restartPolicy: Always
