apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
    - name: "6379"
      port: {{ .Values.redisPort }}
      targetPort: {{ .Values.redisPort }}
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
