apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis
  name: redis
spec:
  ports:
    - port: {{ .Values.REDIS_PORT }}
      targetPort: {{ .Values.REDIS_PORT }}
  selector:
    service: redis
status:
  loadBalancer: {}
